database = [
    {
        "id": 1,
        "tags": ["govt", "verified"],
        "name": "Subhasgram Government Hospital",
        "address": "Subhasgram, Kolkata, West Bengal",
        "pincode": 700147,
        "plusCode": "7MJCCC8H+XF",
        "placeID": "ChIJI9WD5ohtAjoRB3P_8-dm3Lo",
        "stocks": {
            "A": {"+": 23, "-": 12},
            "B": {"+": 3, "-": 1},
            "AB": {"+": 123, "-": 2},
            "O": {"+": 28, "-": 0},
        },
        "lastUpdate": "2022-02-27T12:58:00.000Z",
    },
    {
        "id": 2,
        "tags": ["govt", "verified"],
        "name": "Baruipur S.D. Hospital",
        "address": "Kulpi Road, Baruipur, Kolkata",
        "pincode": 700144,
        "plusCode": "7MJC9C5M+MC",
        "placeID": "ChIJzSAkIMFtAjoRG1dIsg8RMe8",
        "stocks": {
            "A": {"+": 7, "-": 12},
            "B": {"+": 0, "-": 0},
            "AB": {"+": 17, "-": 9},
            "O": {"+": 5, "-": 0},
        },
        "lastUpdate": "2022-03-03T01:19:00.000Z",
    },
    {
        "id": 3,
        "tags": ["govt", "verified"],
        "name": "Ramakrishna Mission Seva Pratishthan (Shishu Mongol Hospital)",
        "address": "Sarat Bose Road, Hazra, Kalighat, Kolkata, West Bengal",
        "pincode": 700029,
        "plusCode": "7MJCG9F2+8R",
        "placeID": "ChIJ-y0c5Et3AjoRfkAkC-vpRlY",
        "stocks": {
            "A": {"+": 17, "-": 5},
            "B": {"+": 13, "-": 0},
            "AB": {"+": 5, "-": 0},
            "O": {"+": 3, "-": 1},
        },
        "lastUpdate": "2022-03-03T02:48:00.000Z",
    },
    {
        "id": 4,
        "name": "Seth Sukhlal Karnani Memorial Hospital",
        "address": "SSKM Hospital Rd, Bhowanipore, Kolkata, West Bengal",
        "pincode": 700020,
        "plusCode": "7MJCG8QR+VV",
        "placeID": "ChIJ91BnEk53AjoRa-dlx1t6HYE",
        "stocks": {
            "A": {"+": 11, "-": 8},
            "B": {"+": 10, "-": 0},
            "AB": {"+": 12, "-": 15},
            "O": {"+": 5, "-": 0}
        },
        "lastUpdate": "2022-03-09T05:58:51.276Z",
    },
]
